CREATE TABLE departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    status text NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT ck_departments_name_nonblank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_departments_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_departments_status_id
    ON departments (status, department_id);

CREATE TABLE roles (
    role_code text NOT NULL,
    name text NOT NULL,
    status text NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_code),
    CONSTRAINT ck_roles_name_nonblank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_roles_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_roles_status_code
    ON roles (status, role_code);

CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL,
    password_hash text NOT NULL,
    name text NOT NULL,
    department_id bigint,
    status text NOT NULL,
    nickname text,
    profile_image_url text,
    created_at timestamp with time zone NOT NULL,
    last_login_at timestamp with time zone,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED'))
);

CREATE INDEX ix_users_department_id_user_id
    ON users (department_id, user_id);

CREATE INDEX ix_users_status_user_id
    ON users (status, user_id);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role_code text NOT NULL,
    granted_by_user_id bigint NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_code),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_code) REFERENCES roles (role_code),
    CONSTRAINT fk_user_roles_granted_by_user
        FOREIGN KEY (granted_by_user_id) REFERENCES users (user_id)
);

CREATE INDEX ix_user_roles_role_code_user_id
    ON user_roles (role_code, user_id);
