CREATE TABLE file_objects (
    file_object_id bigint GENERATED BY DEFAULT AS IDENTITY,
    content_sha256 char(64) NOT NULL,
    file_size bigint NOT NULL,
    original_filename text NOT NULL,
    content_type text NOT NULL,
    document_type text NOT NULL,
    storage_provider text NOT NULL,
    storage_namespace text NOT NULL,
    storage_key text NOT NULL,
    CONSTRAINT pk_file_objects PRIMARY KEY (file_object_id),
    CONSTRAINT uq_file_objects_digest_size
        UNIQUE (content_sha256, file_size),
    CONSTRAINT uq_file_objects_storage_location
        UNIQUE (storage_provider, storage_namespace, storage_key),
    CONSTRAINT ck_file_objects_sha256
        CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_file_objects_size
        CHECK (file_size > 0 AND file_size <= 52428800),
    CONSTRAINT ck_file_objects_filename
        CHECK (btrim(original_filename) <> ''),
    CONSTRAINT ck_file_objects_content_type
        CHECK (btrim(content_type) <> ''),
    CONSTRAINT ck_file_objects_document_type
        CHECK (document_type IN ('PDF', 'TXT', 'MD', 'DOCX', 'HTML', 'ETC')),
    CONSTRAINT ck_file_objects_storage_provider
        CHECK (storage_provider IN ('MINIO', 'S3', 'LOCAL')),
    CONSTRAINT ck_file_objects_storage_namespace
        CHECK (btrim(storage_namespace) <> ''),
    CONSTRAINT ck_file_objects_storage_key
        CHECK (btrim(storage_key) <> '')
);

CREATE TABLE documents (
    document_id bigint GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    description text,
    document_type text NOT NULL,
    source_type text NOT NULL,
    status text NOT NULL,
    visibility text NOT NULL,
    owner_user_id bigint NOT NULL,
    owner_name text NOT NULL,
    current_version_id bigint,
    latest_version_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT pk_documents PRIMARY KEY (document_id),
    CONSTRAINT fk_documents_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_documents_title
        CHECK (btrim(title) <> '' AND char_length(title) <= 500),
    CONSTRAINT ck_documents_description
        CHECK (description IS NULL OR btrim(description) <> ''),
    CONSTRAINT ck_documents_document_type
        CHECK (document_type IN ('PDF', 'TXT', 'MD', 'DOCX', 'HTML', 'ETC')),
    CONSTRAINT ck_documents_source_type
        CHECK (source_type IN ('UPLOAD', 'URL', 'API', 'MCP')),
    CONSTRAINT ck_documents_status
        CHECK (status IN (
            'DRAFT', 'UPLOADED', 'INDEXING', 'INDEXED',
            'FAILED', 'ARCHIVED', 'DELETED'
        )),
    CONSTRAINT ck_documents_visibility
        CHECK (visibility IN ('PRIVATE', 'COLLECTION', 'DEPARTMENT', 'PUBLIC')),
    CONSTRAINT ck_documents_owner_name
        CHECK (btrim(owner_name) <> ''),
    CONSTRAINT ck_documents_deleted_at
        CHECK (
            (status = 'DELETED' AND deleted_at IS NOT NULL)
            OR (status <> 'DELETED' AND deleted_at IS NULL)
        )
);

CREATE TABLE document_versions (
    document_version_id bigint GENERATED BY DEFAULT AS IDENTITY,
    document_id bigint NOT NULL,
    version_no integer NOT NULL,
    file_object_id bigint NOT NULL,
    title_snapshot text NOT NULL,
    status text NOT NULL,
    created_at timestamptz NOT NULL,
    indexed_at timestamptz,
    CONSTRAINT pk_document_versions PRIMARY KEY (document_version_id),
    CONSTRAINT uq_document_versions_document_version_no
        UNIQUE (document_id, version_no),
    CONSTRAINT uq_document_versions_document_version_id
        UNIQUE (document_id, document_version_id),
    CONSTRAINT fk_document_versions_document
        FOREIGN KEY (document_id) REFERENCES documents (document_id),
    CONSTRAINT fk_document_versions_file_object
        FOREIGN KEY (file_object_id) REFERENCES file_objects (file_object_id),
    CONSTRAINT ck_document_versions_version_no
        CHECK (version_no >= 1),
    CONSTRAINT ck_document_versions_title_snapshot
        CHECK (btrim(title_snapshot) <> '' AND char_length(title_snapshot) <= 500),
    CONSTRAINT ck_document_versions_status
        CHECK (status IN (
            'UPLOADED', 'PARSING', 'CHUNKED',
            'EMBEDDING', 'INDEXED', 'FAILED'
        ))
);

ALTER TABLE documents
    ADD CONSTRAINT fk_documents_current_version
        FOREIGN KEY (document_id, current_version_id)
        REFERENCES document_versions (document_id, document_version_id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_documents_latest_version
        FOREIGN KEY (document_id, latest_version_id)
        REFERENCES document_versions (document_id, document_version_id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX ix_documents_owner_status_id
    ON documents (owner_user_id, status, document_id);

CREATE INDEX ix_documents_status_id
    ON documents (status, document_id);

CREATE INDEX ix_document_versions_document_version_no_desc
    ON document_versions (document_id, version_no DESC);

CREATE INDEX ix_document_versions_status_document
    ON document_versions (status, document_id);

CREATE UNIQUE INDEX uq_document_versions_one_active
    ON document_versions (document_id)
    WHERE status IN ('UPLOADED', 'PARSING', 'CHUNKED', 'EMBEDDING');
