CREATE TABLE collections (
    collection_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    owner_user_id bigint NOT NULL,
    parent_id bigint,
    visibility text NOT NULL DEFAULT 'PRIVATE',
    status text NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT pk_collections PRIMARY KEY (collection_id),
    CONSTRAINT fk_collections_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_collections_parent
        FOREIGN KEY (parent_id) REFERENCES collections (collection_id),
    CONSTRAINT ck_collections_name
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_collections_not_own_parent
        CHECK (parent_id IS NULL OR parent_id <> collection_id),
    CONSTRAINT ck_collections_visibility
        CHECK (visibility IN ('PRIVATE', 'COLLECTION', 'DEPARTMENT', 'PUBLIC')),
    CONSTRAINT ck_collections_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED'))
);

CREATE TABLE collection_documents (
    collection_id bigint NOT NULL,
    document_id bigint NOT NULL,
    CONSTRAINT pk_collection_documents
        PRIMARY KEY (collection_id, document_id),
    CONSTRAINT fk_collection_documents_collection
        FOREIGN KEY (collection_id) REFERENCES collections (collection_id),
    CONSTRAINT fk_collection_documents_document
        FOREIGN KEY (document_id) REFERENCES documents (document_id)
);

CREATE TABLE direct_permissions (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY,
    permission_kind text NOT NULL,
    target_type text NOT NULL,
    document_id bigint,
    collection_id bigint,
    user_id bigint,
    department_id bigint,
    role_code text,
    expires_at timestamptz,
    CONSTRAINT pk_direct_permissions PRIMARY KEY (permission_id),
    CONSTRAINT fk_direct_permissions_document
        FOREIGN KEY (document_id) REFERENCES documents (document_id),
    CONSTRAINT fk_direct_permissions_collection
        FOREIGN KEY (collection_id) REFERENCES collections (collection_id),
    CONSTRAINT fk_direct_permissions_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_direct_permissions_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT fk_direct_permissions_role
        FOREIGN KEY (role_code) REFERENCES roles (role_code),
    CONSTRAINT ck_direct_permissions_permission_kind
        CHECK (permission_kind IN ('READ', 'WRITE', 'ADMIN')),
    CONSTRAINT ck_direct_permissions_target_type
        CHECK (target_type IN ('USER', 'DEPARTMENT', 'ROLE')),
    CONSTRAINT ck_direct_permissions_one_resource
        CHECK (
            (document_id IS NOT NULL AND collection_id IS NULL)
            OR (document_id IS NULL AND collection_id IS NOT NULL)
        ),
    CONSTRAINT ck_direct_permissions_target_shape
        CHECK (
            (
                target_type = 'USER'
                AND user_id IS NOT NULL
                AND department_id IS NULL
                AND role_code IS NULL
            )
            OR (
                target_type = 'DEPARTMENT'
                AND user_id IS NULL
                AND department_id IS NOT NULL
                AND role_code IS NULL
            )
            OR (
                target_type = 'ROLE'
                AND user_id IS NULL
                AND department_id IS NULL
                AND role_code IS NOT NULL
            )
        ),
    CONSTRAINT ck_direct_permissions_role_not_user
        CHECK (target_type <> 'ROLE' OR role_code <> 'USER')
);

CREATE TABLE document_permission_cache (
    permission_id bigint NOT NULL,
    document_id bigint NOT NULL,
    CONSTRAINT pk_document_permission_cache
        PRIMARY KEY (permission_id, document_id),
    CONSTRAINT fk_document_permission_cache_permission
        FOREIGN KEY (permission_id) REFERENCES direct_permissions (permission_id),
    CONSTRAINT fk_document_permission_cache_document
        FOREIGN KEY (document_id) REFERENCES documents (document_id)
);

CREATE INDEX ix_collections_parent_id
    ON collections (parent_id, collection_id);

CREATE INDEX ix_collections_owner_status_id
    ON collections (owner_user_id, status, collection_id);

CREATE INDEX ix_collection_documents_document_id
    ON collection_documents (document_id, collection_id);

CREATE INDEX ix_direct_permissions_document
    ON direct_permissions (document_id, permission_id)
    WHERE document_id IS NOT NULL;

CREATE INDEX ix_direct_permissions_collection
    ON direct_permissions (collection_id, permission_id)
    WHERE collection_id IS NOT NULL;

CREATE INDEX ix_direct_permissions_user
    ON direct_permissions (user_id, permission_id)
    WHERE target_type = 'USER';

CREATE INDEX ix_direct_permissions_department
    ON direct_permissions (department_id, permission_id)
    WHERE target_type = 'DEPARTMENT';

CREATE INDEX ix_direct_permissions_role
    ON direct_permissions (role_code, permission_id)
    WHERE target_type = 'ROLE';

CREATE INDEX ix_document_permission_cache_document
    ON document_permission_cache (document_id, permission_id);
