CREATE TABLE indexing_workers (
    worker_id bigint GENERATED BY DEFAULT AS IDENTITY,
    instance_id text NOT NULL,
    name text NOT NULL,
    hostname text NOT NULL,
    ip text,
    status text NOT NULL,
    last_heartbeat timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    stopped_at timestamptz,
    CONSTRAINT pk_indexing_workers PRIMARY KEY (worker_id),
    CONSTRAINT ck_indexing_workers_instance_id_nonblank
        CHECK (btrim(instance_id) <> ''),
    CONSTRAINT ck_indexing_workers_name_nonblank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_indexing_workers_hostname_nonblank
        CHECK (btrim(hostname) <> ''),
    CONSTRAINT ck_indexing_workers_status
        CHECK (status IN ('ACTIVE', 'IDLE', 'STOPPED', 'DEAD'))
);

CREATE INDEX ix_indexing_workers_instance
    ON indexing_workers (instance_id, worker_id);

CREATE INDEX ix_indexing_workers_status_heartbeat
    ON indexing_workers (status, last_heartbeat, worker_id);


CREATE TABLE indexing_jobs (
    job_id bigint GENERATED BY DEFAULT AS IDENTITY,
    document_version_id bigint NOT NULL,
    status text NOT NULL,
    priority integer NOT NULL DEFAULT 0,
    max_retries integer NOT NULL DEFAULT 3,
    retry_count integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL,
    next_run_at timestamptz,
    worker_id bigint,
    claim_token uuid,
    locked_at timestamptz,
    lease_expires_at timestamptz,
    first_started_at timestamptz,
    completed_at timestamptz,
    failed_at timestamptz,
    failure_type text,
    error_message text,
    CONSTRAINT pk_indexing_jobs PRIMARY KEY (job_id),
    CONSTRAINT uq_indexing_jobs_document_version UNIQUE (document_version_id),
    CONSTRAINT fk_indexing_jobs_document_version
        FOREIGN KEY (document_version_id)
        REFERENCES document_versions (document_version_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_indexing_jobs_worker
        FOREIGN KEY (worker_id)
        REFERENCES indexing_workers (worker_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_indexing_jobs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', 'CANCELED')),
    CONSTRAINT ck_indexing_jobs_retry_counts
        CHECK (
            max_retries >= 0
            AND retry_count >= 0
            AND retry_count <= max_retries
        ),
    CONSTRAINT ck_indexing_jobs_failure_type
        CHECK (
            failure_type IS NULL
            OR failure_type IN (
                'STORAGE_UNAVAILABLE',
                'STORAGE_CONFIGURATION_INVALID',
                'STORAGE_OBJECT_MISSING',
                'DOCUMENT_CONTENT_INVALID',
                'EMBEDDING_PROVIDER_UNAVAILABLE',
                'EMBEDDING_PROVIDER_OVERLOADED',
                'EMBEDDING_PROVIDER_TIMEOUT',
                'EMBEDDING_PROVIDER_CIRCUIT_OPEN',
                'EMBEDDING_REQUEST_INVALID',
                'EMBEDDING_RESULT_INVALID',
                'INDEXING_STATE_INCONSISTENT',
                'WORKER_INTERNAL_ERROR'
            )
        ),
    CONSTRAINT ck_indexing_jobs_ownership_complete
        CHECK (
            (status IN ('PROCESSING', 'INDEXED')
                AND num_nonnulls(
                    worker_id, claim_token, locked_at, lease_expires_at
                ) = 4)
            OR
            (status IN ('PENDING', 'FAILED', 'CANCELED')
                AND num_nonnulls(
                    worker_id, claim_token, locked_at, lease_expires_at
                ) = 0)
        ),
    CONSTRAINT ck_indexing_jobs_lease_order
        CHECK (
            lease_expires_at IS NULL
            OR lease_expires_at > locked_at
        ),
    CONSTRAINT ck_indexing_jobs_terminal_times
        CHECK (
            (status = 'INDEXED' AND completed_at IS NOT NULL AND failed_at IS NULL)
            OR (status = 'FAILED' AND failed_at IS NOT NULL AND completed_at IS NULL)
            OR (status IN ('PENDING', 'PROCESSING', 'CANCELED')
                AND completed_at IS NULL
                AND failed_at IS NULL)
        )
);

CREATE INDEX ix_indexing_jobs_claim
    ON indexing_jobs (priority DESC, created_at, job_id)
    WHERE status = 'PENDING';

CREATE INDEX ix_indexing_jobs_pending_next_run
    ON indexing_jobs (next_run_at, job_id)
    WHERE status = 'PENDING';

CREATE INDEX ix_indexing_jobs_recovery
    ON indexing_jobs (lease_expires_at, job_id)
    WHERE status = 'PROCESSING';


CREATE TABLE indexing_attempts (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_id bigint NOT NULL,
    attempt_no integer NOT NULL,
    worker_id bigint NOT NULL,
    claim_token uuid NOT NULL,
    status text NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at timestamptz,
    duration_ms bigint,
    failure_type text,
    error_message text,
    result_job_status text,
    result_retry_count integer,
    result_next_run_at timestamptz,
    CONSTRAINT pk_indexing_attempts PRIMARY KEY (attempt_id),
    CONSTRAINT uq_indexing_attempts_job_number UNIQUE (job_id, attempt_no),
    CONSTRAINT uq_indexing_attempts_job_claim UNIQUE (job_id, claim_token),
    CONSTRAINT fk_indexing_attempts_job
        FOREIGN KEY (job_id)
        REFERENCES indexing_jobs (job_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_indexing_attempts_worker
        FOREIGN KEY (worker_id)
        REFERENCES indexing_workers (worker_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_indexing_attempts_number
        CHECK (attempt_no >= 1),
    CONSTRAINT ck_indexing_attempts_status
        CHECK (status IN ('STARTED', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_indexing_attempts_duration
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_indexing_attempts_time_order
        CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT ck_indexing_attempts_failure_type
        CHECK (
            failure_type IS NULL
            OR failure_type IN (
                'STORAGE_UNAVAILABLE',
                'STORAGE_CONFIGURATION_INVALID',
                'STORAGE_OBJECT_MISSING',
                'DOCUMENT_CONTENT_INVALID',
                'EMBEDDING_PROVIDER_UNAVAILABLE',
                'EMBEDDING_PROVIDER_OVERLOADED',
                'EMBEDDING_PROVIDER_TIMEOUT',
                'EMBEDDING_PROVIDER_CIRCUIT_OPEN',
                'EMBEDDING_REQUEST_INVALID',
                'EMBEDDING_RESULT_INVALID',
                'INDEXING_STATE_INCONSISTENT',
                'WORKER_INTERNAL_ERROR'
            )
        ),
    CONSTRAINT ck_indexing_attempts_result_status
        CHECK (result_job_status IS NULL OR result_job_status IN ('PENDING', 'FAILED')),
    CONSTRAINT ck_indexing_attempts_result_retry_count
        CHECK (result_retry_count IS NULL OR result_retry_count >= 0),
    CONSTRAINT ck_indexing_attempts_state_fields
        CHECK (
            (status = 'STARTED'
                AND ended_at IS NULL
                AND duration_ms IS NULL
                AND failure_type IS NULL
                AND error_message IS NULL
                AND result_job_status IS NULL
                AND result_retry_count IS NULL
                AND result_next_run_at IS NULL)
            OR
            (status = 'SUCCESS'
                AND ended_at IS NOT NULL
                AND duration_ms IS NOT NULL
                AND failure_type IS NULL
                AND error_message IS NULL
                AND result_job_status IS NULL
                AND result_retry_count IS NULL
                AND result_next_run_at IS NULL)
            OR
            (status = 'FAILED'
                AND ended_at IS NOT NULL
                AND duration_ms IS NOT NULL
                AND failure_type IS NOT NULL
                AND error_message IS NOT NULL
                AND result_job_status IS NOT NULL
                AND result_retry_count IS NOT NULL)
        )
);


CREATE TABLE indexing_events (
    indexing_event_id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_id bigint NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_indexing_events PRIMARY KEY (indexing_event_id),
    CONSTRAINT fk_indexing_events_job
        FOREIGN KEY (job_id)
        REFERENCES indexing_jobs (job_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_indexing_events_type
        CHECK (
            event_type IN (
                'JOB_CREATED',
                'LOCKED',
                'PARSE_STARTED',
                'PARSE_FAILED',
                'CHUNKED',
                'EMBEDDING_STARTED',
                'EMBEDDING_FAILED',
                'INDEXED',
                'LEASE_EXPIRED',
                'FAILED',
                'RETRY',
                'MANUAL_RETRY'
            )
        ),
    CONSTRAINT ck_indexing_events_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE UNIQUE INDEX uq_indexing_events_job_indexed
    ON indexing_events (job_id)
    WHERE event_type = 'INDEXED';

CREATE INDEX ix_indexing_events_job_time
    ON indexing_events (job_id, occurred_at, indexing_event_id);


CREATE TABLE document_chunks (
    document_version_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    start_offset integer NOT NULL,
    end_offset integer NOT NULL,
    content text NOT NULL,
    content_sha256 char(64) NOT NULL,
    token_estimate integer NOT NULL,
    page_number integer,
    section_title text,
    CONSTRAINT pk_document_chunks PRIMARY KEY (document_version_id, chunk_index),
    CONSTRAINT fk_document_chunks_version
        FOREIGN KEY (document_version_id)
        REFERENCES document_versions (document_version_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_document_chunks_index
        CHECK (chunk_index >= 0),
    CONSTRAINT ck_document_chunks_offsets
        CHECK (start_offset >= 0 AND end_offset >= start_offset),
    CONSTRAINT ck_document_chunks_sha256
        CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_chunks_token_estimate
        CHECK (token_estimate >= 0),
    CONSTRAINT ck_document_chunks_page_number
        CHECK (page_number IS NULL OR page_number >= 1)
);


CREATE TABLE embedding_models (
    embedding_model_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    dimension integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    searchable boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_embedding_models PRIMARY KEY (embedding_model_id),
    CONSTRAINT ck_embedding_models_name_nonblank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_embedding_models_dimension
        CHECK (dimension > 0)
);

CREATE INDEX ix_embedding_models_selection
    ON embedding_models (active, searchable, embedding_model_id);


CREATE TABLE document_vectors (
    vector_id bigint GENERATED BY DEFAULT AS IDENTITY,
    document_version_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    embedding_model_id bigint NOT NULL,
    embedding vector NOT NULL,
    status text NOT NULL,
    CONSTRAINT pk_document_vectors PRIMARY KEY (vector_id),
    CONSTRAINT uq_document_vectors_chunk_model
        UNIQUE (document_version_id, chunk_index, embedding_model_id),
    CONSTRAINT fk_document_vectors_chunk
        FOREIGN KEY (document_version_id, chunk_index)
        REFERENCES document_chunks (document_version_id, chunk_index)
        ON DELETE RESTRICT,
    CONSTRAINT fk_document_vectors_model
        FOREIGN KEY (embedding_model_id)
        REFERENCES embedding_models (embedding_model_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_document_vectors_status
        CHECK (status IN ('ACTIVE', 'STALE', 'DELETED'))
);

CREATE INDEX ix_document_vectors_model_status_version
    ON document_vectors (embedding_model_id, status, document_version_id);
