CREATE TABLE mcp_tokens (
    token_id uuid PRIMARY KEY,
    owner_user_id bigint NOT NULL,
    key_sha256 char(64) NOT NULL,
    created_at timestamptz NOT NULL,
    last_used_at timestamptz,
    revoked_at timestamptz,
    CONSTRAINT fk_mcp_tokens_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT uq_mcp_tokens_key_sha256 UNIQUE (key_sha256),
    CONSTRAINT ck_mcp_tokens_key_sha256
        CHECK (key_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_mcp_tokens_time_order
        CHECK (
            (last_used_at IS NULL OR last_used_at >= created_at)
            AND (revoked_at IS NULL OR revoked_at >= created_at)
            AND (
                last_used_at IS NULL
                OR revoked_at IS NULL
                OR revoked_at >= last_used_at
            )
        )
);

CREATE INDEX ix_mcp_tokens_owner_created
    ON mcp_tokens (owner_user_id, created_at, token_id);


CREATE TABLE search_requests (
    search_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id text NOT NULL,
    query_text text NOT NULL,
    requested_at timestamptz NOT NULL,
    duration_ms double precision NOT NULL,
    results_count integer NOT NULL,
    status text NOT NULL,
    settings_hash char(64) NOT NULL,
    CONSTRAINT ck_search_requests_requester_nonblank
        CHECK (btrim(requester_id) <> ''),
    CONSTRAINT ck_search_requests_duration
        CHECK (
            duration_ms >= 0.0
            AND duration_ms < 'Infinity'::double precision
        ),
    CONSTRAINT ck_search_requests_results_count
        CHECK (results_count >= 0),
    CONSTRAINT ck_search_requests_status_nonblank
        CHECK (btrim(status) <> ''),
    CONSTRAINT ck_search_requests_settings_hash
        CHECK (settings_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_search_requests_retention
    ON search_requests (requested_at, search_id);

CREATE INDEX ix_search_requests_requester_recent
    ON search_requests (requester_id, requested_at DESC, search_id DESC);


CREATE TABLE search_answers (
    search_id bigint PRIMARY KEY,
    answer_text text NOT NULL,
    status text NOT NULL,
    CONSTRAINT fk_search_answers_request
        FOREIGN KEY (search_id)
        REFERENCES search_requests (search_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_search_answers_status_nonblank
        CHECK (btrim(status) <> '')
);


CREATE TABLE search_citations (
    search_id bigint NOT NULL,
    rank integer NOT NULL,
    chunk_id uuid NOT NULL,
    document_id uuid NOT NULL,
    CONSTRAINT pk_search_citations PRIMARY KEY (search_id, rank),
    CONSTRAINT fk_search_citations_request
        FOREIGN KEY (search_id)
        REFERENCES search_requests (search_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_search_citations_rank
        CHECK (rank >= 1)
);

CREATE INDEX ix_search_citations_document
    ON search_citations (document_id, search_id);

COMMENT ON TABLE search_requests IS
    'Retention removes rows with requested_at strictly earlier than the cutoff; exact-cutoff rows remain.';
