"""Persistence boundary for the document ledger."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from .database import CommitOutcomeUnknown

__all__ = ["CommitOutcomeUnknown", "DocumentLedgerStore"]


class DocumentLedgerStore(Protocol):
    """State-only document persistence; callers retain every domain decision."""

    def read(self) -> AbstractContextManager[None]: ...

    def transaction(self) -> AbstractContextManager[None]: ...

    def next_id(self, kind: str) -> int: ...

    def lock_job(self, job_id: int) -> None: ...

    def lock_version(self, version_id: int) -> None: ...

    def lock_document(self, document_id: int) -> None: ...

    def find_file(self, digest: str, size: int) -> Any | None: ...

    def file(self, file_id: int) -> Any | None: ...

    def insert_file_if_absent(self, row: Any) -> bool: ...

    def document(self, document_id: int) -> Any | None: ...

    def documents(self) -> tuple[Any, ...]: ...

    def insert_document(self, row: Any) -> None: ...

    def save_document(self, row: Any) -> None: ...

    def version(self, version_id: int) -> Any | None: ...

    def versions(self, document_id: int) -> tuple[Any, ...]: ...

    def insert_version(self, row: Any) -> None: ...

    def save_version(self, row: Any) -> None: ...

    def job(self, job_id: int) -> Any | None: ...

    def job_for_version(self, version_id: int) -> Any | None: ...

    def insert_job(self, row: Any) -> None: ...

    def save_job(self, row: Any) -> None: ...

    def chunks(self, version_id: int) -> tuple[Any, ...] | None: ...

    def insert_chunks_if_absent(
        self, version_id: int, rows: tuple[Any, ...]
    ) -> tuple[bool, tuple[Any, ...]]: ...

    def replace_chunks(self, version_id: int, rows: tuple[Any, ...]) -> None: ...

    def append_event(self, row: Any) -> None: ...

    def has_documents(self) -> bool: ...

    def compatibility_state(self) -> Any: ...

    def compatibility_next_ids(self) -> dict[str, int]: ...
