"""VectorShelf platform response, error, security, and CORS behavior."""

from .core import (
    ALLOWED_CORS_ORIGINS,
    AccessDeniedError,
    AuthenticationError,
    BodyValidationError,
    DataAccessError,
    IntegrityConstraintError,
    MethodNotAllowedError,
    MAX_REQUEST_BYTES,
    PlatformApp,
    PlatformError,
    RequestValidationError,
    UnsupportedMediaTypeError,
    UploadTooLargeError,
    error_response,
    origin_allowed,
    page_payload,
    success_response,
)
from .websocket import (
    DestinationPolicy,
    InMemoryStompBroker,
    StompConnectionRejected,
    StompFrame,
    StompFrameProcessor,
    StompFrameRejected,
    StompHandshakeRejected,
    StompRejected,
    StompWebSocketGateway,
)
from .sockjs import SockJsHttpTransport

__all__ = [
    "ALLOWED_CORS_ORIGINS",
    "AccessDeniedError",
    "AuthenticationError",
    "BodyValidationError",
    "DataAccessError",
    "IntegrityConstraintError",
    "DestinationPolicy",
    "InMemoryStompBroker",
    "MethodNotAllowedError",
    "MAX_REQUEST_BYTES",
    "PlatformApp",
    "PlatformError",
    "RequestValidationError",
    "StompConnectionRejected",
    "StompFrame",
    "StompFrameProcessor",
    "SockJsHttpTransport",
    "StompFrameRejected",
    "StompHandshakeRejected",
    "StompRejected",
    "StompWebSocketGateway",
    "UnsupportedMediaTypeError",
    "UploadTooLargeError",
    "error_response",
    "origin_allowed",
    "page_payload",
    "success_response",
]
